# coding: utf-8
"""
Basic configuration for running tests and generating documentation.

Because Django apps are so tied to Django, it is necessary to configure
Django's settings module before tests can be run or documentation can
be successfully generated by Sphinx.
"""
import os

from django.conf import settings

SITE_ROOT = os.path.dirname(os.path.realpath(__file__))

if not (settings.configured or os.environ.get('DJANGO_SETTINGS_MODULE')):
  settings.configure(
    DATABASES={
      'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
        },
      },
    INSTALLED_APPS=[
      'djredis',
      'south',
      ],
    TEMPLATE_DIRS=(
      os.path.join(SITE_ROOT, 'djredis/templates'),
      ),
    ROOT_URLCONF='djredis.tests.test_urls',
    FIXTURE_DIRS=(
      os.path.join(SITE_ROOT, 'djredis/fixtures'),
      ),
    DEBUG=False,
    )
